import Head from 'next/head'
import Image from 'next/image'
import Cours from '@models/Cours'
import styles from '@styles/Home.module.css'

export default function Home() {

  const titre = () => {
    const cours = new Cours({ titre: "mon premier cours" });
    cours.titre = "   azddazd    .";
    return cours.titre;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Markdown App</h1>
        <p>notre application commence ici...☕️</p>
        <p>{titre()}</p>
      </main>
    </div>
  )
}
